spring:
 cloud:
   gateway:
     routes:
       - id: speedy-app
         uri: lb://SPEEDY-APP
         predicates:
           - Path=/speedy/**



       - id: restaurant-service
         uri: lb://RESTAURANT-SERVICE
         predicates:
           - Path=/restaurant/**


 application:
   name: SPEEDY-GATEWAY


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/